# Generated by Django 6.0.6 on 2026-06-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_type', models.CharField(choices=[('QUALIFYING_PREDICTIONS', 'Qualifying Predictions'), ('QUALIFYING_RESULTS', 'Qualifying Results'), ('OTHER_VIDEOS', 'Other Videos'), ('SHORTS', 'Shorts')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('upload_date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('watch_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
    ]
